version: 1.0.{build}

os: Visual Studio 2015

matrix:
  fast_finish: true

platform:
  #- x64

#configuration:
  #- Debug
  #- Release

clone_folder: c:\projects\cexpr

build:
  parallel: false
  project: c:\projects\cexpr\build\cexpr.sln
  verbosity: minimal

before_build:
  - cd c:\projects\cexpr
  - md build
  - cd build
  - cmake -G"Visual Studio 14 2015 Win64" ..

build_script:
 - cd c:\projects\cexpr\build
 - msbuild /target:all_tests /p:Configuration=Debug;Platform=x64 cexpr.sln
 - msbuild /target:all_tests /p:Configuration=Release;Platform=x64 cexpr.sln

test_script:
 - cd c:\projects\cexpr\build
 - cmd: ctest -C Debug -VV
 - cmd: ctest -C Release -VV
